name: Compile & Push

"on":
  push:
    paths:
    - cv.tex

jobs:
  build-latex:
    runs-on: ubuntu-latest
    env:
      CV_FILENAME: pontuscurtsson-cv.pdf
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Github Action for LaTeX
      uses: xu-cheng/latex-action@3.3.0
      with:
        root_file: cv.tex

    - name: Commit
      run: |
        mv cv.pdf "$CV_FILENAME"
        git config --local user.name 'github-actions[bot]'
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'
        git add "$CV_FILENAME"
        git commit  -m "Update CV"

    - name: Push
      uses: ad-m/github-push-action@master
